apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    pg-group : postgres
spec:
  type: NodePort
  selector:
    pg-group : postgres
  ports:
    - port: 5432
      name: postgres
      targetPort: 5432
      protocol: TCP
      nodePort: 5434