apiVersion: v1
kind: Service
metadata:
  name: position-service
  labels:
    position-group : position
spec:
  selector:
    position-group : position
  ports:
    - port: 5301
      targetPort: 5301
      protocol: TCP