apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    client-group : client
spec:
  type: NodePort
  selector:
    client-group : client
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 8999